version: "3.8"
services:
    db:
        image: cassandra:3.11
        ports:
            - 7000:7000
        working_dir: /rcdb
        volumes:
            - rcdb-data:/var/lib/cassandra
        environment:
            CASSANDRA_CLUSTER_NAME: rcdb
volumes:
    rcdb-data: